### ISSUE TITLE
Feature request: tagged logging support

### ISSUE THREAD

**Issue by sadovnik** [mainameiz/huyegger#1]
It would be nice if Huyegger support [tagged logging](http://api.rubyonrails.org/classes/ActiveSupport/TaggedLogging.html).

**Comment by sadovnik** [comment]
Hello there! Any news? 🌚🌚🌚🌚🌚🌚

**Comment by sadovnik** [comment]
🌝

**Comment by ayrat555** [comment]
Still no news? I can't wait for this feature

**Comment by sadovnik** [comment]
🌚
